data_name: isprs_postdam
data_zip: isprs_postdam.zip
data_dir: dataset/isprs_postdam

image_dir: images
label_dir: labels
split_dir: splits

data_split_ratio: [0.7, 0.15, 0.15]
split_seed: 42
overwrite_splits: false
input_size: 252

ignore_index: 255
available_bands:
  R: 0
  G: 1
  B: 2
selected_bands: [R, G, B]
class_dict: 
  0:
    name: Impervious surfaces
    rgb : [255, 255, 255]
  1:
    name: Building
    rgb : [0, 0, 255]
  2:
    name: Low vegetation
    rgb : [0, 255, 255]
  3:
    name: Tree
    rgb : [0, 255, 0]
  4:
    name: Car
    rgb : [255, 255, 0]
  255:
    name: Background
    rgb : [255, 0, 0]