# GLOBAL CONFIGURATION
model:
  model_name: UNet
  model_config:
    arch: UNet
    input_channels: 3
  optimizer_config: 
    name: Adam
    lr: 0.001
  loss_config:
    name: CrossEntropyLoss
    weight: null

trainer:
  max_epochs: 100
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      monitor: val_loss
      mode: min
      save_top_k: 1
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      monitor: val_loss
      mode: min
      patience: 10

data:
  train:
    batch_size: 16
    num_workers: 4
    shuffle: true
  val:
    batch_size: 16
    num_workers: 4
    shuffle: false
  test:
    batch_size: 16
    num_workers: 4
    shuffle: false

# Fit configuration for the training loop, such as logging and checkpointing
fit:
  trainer:
    callbacks:
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        monitor: val_loss
        mode: min
        save_top_k: 1
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        monitor: val_loss
        mode: min
        patience: 10
    logger:
      - class_path: lightning.pytorch.loggers.TensorBoardLogger
        save_dir: artifacts

test:
  trainer:
    logger:
      type: TensorBoardLogger
      save_dir: artifacts
      name: semantic_segmentation_test

predict:
  trainer:
    logger:
      type: TensorBoardLogger
      save_dir: artifacts 
      name: semantic_segmentation_predict
      

