schema_version: 2
rasters:
  sentinel_2_l2a:
    variables: [B02, B03, B04, B08]
    coordinates: [x, y]
    require_crs: true
    stac:
      collection: sentinel-2-l2a
      endpoints:
        - planetary_computer
        - cdse
      load:
        bands: [B02, B03, B04, B08]
preprocessing:
  valid_pixels:
    call: geosave_engine.geodata.transform.nodata.to_nan
    kwargs:
      data: !ref sentinel_2_l2a
  image:
    call: geosave_engine.geodata.transform.packing.unpack
    kwargs:
      data: !ref valid_pixels
