schema_version: 2
sources:
  sentinel_2_l2a:
    collection: sentinel-2-l2a
    endpoints:
      - https://planetarycomputer.microsoft.com/api/stac/v1/
      - https://stac.dataspace.copernicus.eu/v1/
    variables: [B02, B03, B04, B08]
    require_crs: true
preprocessing:
  valid_pixels:
    call: !ref sentinel_2_l2a.gs.to_nan
  image:
    call: !ref valid_pixels.gs.unpack
inference:
  image:
    call: !ref image.gs.to_tensor
    kwargs:
      dtype: float32
postprocessing: {}
