"""Build raster Datasets and read them through the `gs` Dataset accessor.

Georeferencing is odc-geo's. GeoSave adds only the CF axis semantics odc
omits, which `write_crs` writes.

Examples:
    A raster carrying no CRS holds pixels without claiming ground position, so
    `GeoRaster.geobox` is None, and members needing ground position refuse.
    Variable access still works:

    >>> png
    <xarray.Dataset> Size: 262kB
    Dimensions:  (y: 512, x: 512)
    Dimensions without coordinates: y, x
    Data variables:
        band     (y, x) uint8 ...

    A georeferenced one carries `spatial_ref`, which odc reads a GeoBox off:

    >>> opened
    <xarray.Dataset> Size: 2MB
    Dimensions:      (time: 2, y: 512, x: 512)
    Coordinates:
      * time         (time) datetime64[ns] 2025-06-01 2025-06-11
      * y            (y) float64 5.0051e+06 5.0051e+06 ... 5.0000e+06
      * x            (x) float64 3.0000e+05 3.0000e+05 ... 3.0511e+05
        spatial_ref  int32 32633
    Data variables:
        red          (time, y, x) uint16 ...
    >>> opened.y.attrs
    {'units': 'metre', 'resolution': -10.0, 'crs': 'EPSG:32633'}

    `write_crs` adds what those axes measure, which odc leaves out:

    >>> opened.gs.write_crs().y.attrs
    {'units': 'metre', 'resolution': -10.0, 'crs': 'EPSG:32633',
     'standard_name': 'projection_y_coordinate', 'axis': 'Y'}

    Geographic grids span `y` and `x` too. CF metadata identifies them as
    latitude and longitude:

    >>> wgs84.red.dims
    ('y', 'x')
    >>> wgs84.y.attrs["standard_name"], wgs84.y.attrs["units"]
    ('latitude', 'degrees_north')
"""

from __future__ import annotations

from pathlib import Path, PurePosixPath
from typing import TYPE_CHECKING, Any, Unpack, cast

import numpy as np
import odc.geo.xr  # noqa: F401  — registers the .odc accessor
import pandas as pd
import xarray as xr
from odc.geo.geobox import GeoBox

import geosave_engine.geodata.attrs as attrs
from geosave_engine.geodata.attrs.headers.geobox import (
    create_header as create_geobox_header,
)
from geosave_engine.geodata.transform import nodata

from .base import GeoRasterAccessor
from geosave_engine.geodata.utils.statistics import statistics
from geosave_engine.geodata.conventions import (
    BAND_DIMENSION,
    CRS_COORDINATE,
    SPATIAL_DIMENSIONS,
)


if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from dask.delayed import Delayed
    from os import PathLike
    from numpy.typing import DTypeLike
    from odc.geo import SomeCRS

    from geosave_engine.geodata.io.raster.netcdf import (
        NetCDFEngine,
        NetCDFWriteOptions,
    )
    from geosave_engine.geodata.io.raster.geotiff import COGWriteOptions
    from geosave_engine.geodata.io.raster.zarr import ZarrWriteOptions
    from geosave_engine.geodata.io.storage import StorageOptions

    import holoviews as hv

    from geosave_engine.geodata import DataArray, Dataset

# Native xarray variables declare all dimensions independently of coordinates.
type RasterVariable = xr.DataArray | tuple[Sequence[str], Any]


def raster(
    variables: Mapping[str, RasterVariable],
    geobox: GeoBox | None = None,
    /,
    *,
    coords: Mapping[str, Any] | None = None,
    nodata: float | int | None = None,
) -> Dataset:
    """Build a raster from variables with explicitly named dimensions.

    Dimension order comes from each variable, independently of coordinate
    order. xarray checks ranks and shared dimension lengths without reading
    lazy pixels. GeoSave checks the trailing spatial pair and places the grid.

    Args:
        variables: Names mapped to native DataArrays or `(dims, pixels)`
            tuples. Every dimension is named, including the spatial pair.
        geobox: Grid placing the trailing `y` and `x` dimensions for any CRS.
            None leaves pixels unreferenced.
        coords: Native xarray coordinates. Omit a dimension's coordinate to
            leave it unlabelled; coordinates do not declare variable dimensions.
        nodata: Fill value written on every variable. None writes no fill value.

    Returns:
        Native Dataset preserving variable order, pixel dtype, and laziness.
        A geobox supplies spatial coordinates and CF/GDAL grid metadata.

    Raises:
        TypeError: A variable has no explicit dimensions.
        ValueError: Variables are empty, xarray dimensions or coordinates are
            incompatible, a variable's trailing dimensions do not match the
            spatial pair, its shape differs from the geobox, or supplied
            coordinates conflict with those generated by the geobox.

    Examples:
        >>> scene = raster(
        ...     {"red": (("time", "y", "x"), cube),
        ...      "dem": (("y", "x"), elevation)},
        ...     geobox,
        ...     coords={"time": labels},
        ... )
        >>> scene.red.dims, scene.dem.dims
        (('time', 'y', 'x'), ('y', 'x'))
    """
    from odc.geo.xr import xr_coords

    if not variables:
        raise ValueError("a raster needs at least one named array")
    for name, value in variables.items():
        if not isinstance(value, (xr.DataArray, tuple)):
            raise TypeError(
                f"{name!r} needs explicit dimensions: use (dims, pixels) or a DataArray"
            )

    built = xr.Dataset(variables, coords=coords)
    spatial_dims = SPATIAL_DIMENSIONS
    for name, band in built.data_vars.items():
        if band.dims[-2:] != spatial_dims:
            raise ValueError(
                f"{name!r}'s trailing dimensions are {band.dims[-2:]} "
                f"but this raster's spatial dimensions are {spatial_dims}"
            )
        if geobox is not None and band.shape[-2:] != tuple(geobox.shape):
            raise ValueError(
                f"{name!r}'s spatial shape is {band.shape[-2:]} "
                f"but the geobox is {tuple(geobox.shape)}"
            )

    if geobox is not None:
        grid_coords = xr_coords(geobox, always_yx=True)
        collisions = sorted(set(built.coords) & set(grid_coords), key=str)
        if collisions:
            raise ValueError(
                f"{collisions} name coordinates this grid already supplies; "
                "let the geobox supply them"
            )
        built = built.assign_coords(grid_coords)

        for band in built.data_vars.values():
            band.encoding["grid_mapping"] = CRS_COORDINATE

        built = attrs.rebase(built, create_geobox_header(geobox))

    if nodata is not None:
        built = built.gs.write_nodata(nodata)

    return cast("Dataset", built)


@xr.register_dataset_accessor("gs")
class GeoRaster(GeoRasterAccessor["Dataset"]):
    """Read and transform one raster Dataset.

    Each member reads only what it needs, so a Dataset mid-computation still
    answers for its grid.

    Args:
        data: Dataset holding one raster.

    Examples:
        >>> ds = source.load(anchor)
        >>> ds.gs.anchor.geobox.shape
        (512, 512)
    """

    @property
    def variables(self) -> tuple[str, ...]:
        """Name the data variables.

        Returns:
            Variable names, in Dataset order.
        """
        return tuple(str(name) for name in self._data.data_vars)

    def _require_variables(self, names: Sequence[str]) -> None:
        """Refuse names this raster carries no data variable for.

        Args:
            names: Data variable names the caller supplied.

        Raises:
            KeyError: A name is not a data variable of this raster.
        """
        unknown = sorted(set(names) - set(self.variables))
        if unknown:
            raise KeyError(
                f"{unknown} are not data variables of this raster; it carries "
                f"{list(self.variables)}"
            )

    @property
    def nodata(self) -> dict[str, float | int | None]:
        """Read the stored value standing for nodata in each variable.

        Returns:
            {
                variable name: its fill value, or None where it carries none,
            }

        Examples:
            >>> ds.gs.nodata
            {'red': 0, 'nir': 0}
        """
        return {name: self._data[name].gs.nodata for name in self.variables}

    def write_crs(self, crs: SomeCRS | None = None) -> Dataset:
        """Write onto the spatial coordinates what they measure.

        The grid decides the answer: a projected raster names
        `projection_y_coordinate` and `projection_x_coordinate`, a geographic
        one `latitude` and `longitude`. No pixel moves; `reproject` does that.

        Args:
            crs: CRS the existing coordinates are in, for a raster that
                carries none or carries the wrong one. None reads the CRS
                the raster already carries.

        Returns:
            New Dataset whose spatial coordinates carry what the grid says of
            them: odc's units, resolution, and CRS, and CF's standard name and
            axis. Their other attrs are replaced.

        Raises:
            ValueError: The raster carries no locatable grid and `crs` names
                none, `crs` names no known reference system, or the raster is
                placed by ground control points rather than a regular grid.

        Examples:
            >>> ds.gs.write_crs("EPSG:32633").y.attrs["standard_name"]
            'projection_y_coordinate'
        """
        result = self._data if crs is None else self._data.odc.assign_crs(crs)
        geobox = result.gs.geobox
        if geobox is None:
            raise ValueError(
                "raster carries no locatable grid and no crs was given; pass "
                "one or assign a CRS first"
            )
        if not isinstance(geobox, GeoBox):
            raise ValueError(
                f"raster is placed by {type(geobox).__name__}, not a regular "
                f"grid, so its axes measure no CF coordinate"
            )
        header = create_geobox_header(geobox)
        return cast("Dataset", attrs.rebase(result, header))

    def write_nodata(
        self,
        value: float | int | None,
        *,
        target: str | Sequence[str] | None = None,
    ) -> Dataset:
        """Write the stored value standing for nodata pixels.

        `Nodata` mirrors the value across both `_FillValue` and odc's own
        `nodata`, so no reader can find the two naming different pixels.

        Args:
            value: Stored value marking nodata. None clears it.
            target: Variable names to write, defaulting to every data variable.

        Returns:
            New Dataset whose named variables carry `value` as their fill.

        Raises:
            KeyError: `target` names something that is not a data variable.
            ValidationError: `value` is not a stored fill value.

        Examples:
            >>> ds.gs.write_nodata(0).red.attrs["_FillValue"]
            0
            >>> ds.gs.write_nodata(-9999, target="elevation")
        """
        if target is None:
            var_names: Sequence[str] = self.variables
        elif isinstance(target, str):
            var_names = (target,)
        else:
            var_names = tuple(target)

        self._require_variables(var_names)

        if value is not None:
            for name in var_names:
                nodata.check_fill_fits(value, self._data[name].dtype, name)

        # Nodata owns both spellings of a fill value, and mirrors them.
        return attrs.rebase(
            self._data, attrs.Nodata(fill_value=value), target=var_names
        )

    def write_rgb(self, red: str, green: str, blue: str) -> Dataset:
        """Name the three variables a true-colour composite draws.

        What a band measures does not say which channel draws it, a false
        colour composite drawing near-infrared as red. Recording the choice is
        also the only way a `GeoStack` panel can name its own bands.

        Args:
            red: Variable drawn as the red channel.
            green: Variable drawn as the green channel.
            blue: Variable drawn as the blue channel.

        Returns:
            New Dataset whose three named variables carry their channel, every
            other variable left uninterpreted.

        Raises:
            KeyError: A name is not a data variable.
            ValueError: One variable is named for two channels.

        Examples:
            >>> ds.gs.write_rgb("B04", "B03", "B02").gs.plot()
        """
        channels = dict(zip(("red", "green", "blue"), (red, green, blue), strict=True))

        self._require_variables(tuple(channels.values()))
        if len(set(channels.values())) < len(channels):
            raise ValueError(
                f"one variable cannot draw two channels, but these name "
                f"{channels}; give each channel its own variable"
            )

        # A band left interpreted would compose a second, stale colour.
        written = attrs.rebase(
            self._data,
            target=self.variables,
            gdal_variable={"colorinterp": None},
        )
        for colour, name in channels.items():
            written = attrs.rebase(
                written, attrs.GDALVariable(colorinterp=colour), target=name
            )
        return written

    def statistics(self) -> pd.DataFrame:
        """Summarise every variable's present pixels, reading each of them.

        Returns:
            One row per variable, in Dataset order, with minimum, maximum,
            mean, population stddev, and valid_percent columns. All axes of
            each variable are reduced together.

        Raises:
            ValueError: A variable holds no present pixel.

        Examples:
            >>> ds.gs.statistics()
                 minimum  maximum  mean  stddev  valid_percent
            red      1.0     96.0  45.6    29.9          100.0
            nir      8.0     98.0  56.7    23.2          100.0
        """
        return statistics(self._data.data_vars)

    def to_array(self, *, dtype: DTypeLike | None = None) -> DataArray:
        """Stack every variable this raster carries into one array.

        No packing or display scaling is applied. A multi-band array keeps
        names on `band`, and `GeoArray.to_raster` stacks it back apart.

        Args:
            dtype: Cast applied to the stacked array. None keeps the source
                dtype, which every stacked variable must then share.

        Returns:
            Array shaped `(*axes, band, y, x)`. Its own attrs are the ones
            every band carries with one value, so it reads as one variable.
            Each band's remaining attrs and this raster's own attrs ride on
            the `band` coordinate as `StackedAttrs`.

        Raises:
            ValueError: This raster carries no variables or already spans the
                stacked axis, the variables carry different non-spatial
                dimensions, or they differ in dtype while `dtype` is None.
            TypeError: An attr has no JSON spelling.

        Examples:
            >>> ds[["ndvi"]].gs.to_array()
            >>> ds[["B04", "B03", "B02"]].gs.to_array()
        """
        array = self._stacked(dtype)
        shared, preserved = attrs.StackedAttrs.from_header(self.attrs)
        header = attrs.AttrsHeader(
            root=shared,
            coords={
                BAND_DIMENSION: attrs.AttrsNamespace(
                    models={attrs.StackedAttrs: preserved}
                )
            },
        )
        array.attrs = {}
        attrs.rebase(array, header, inplace=True)
        return cast("DataArray", array)

    def plot(
        self,
        variable: str | tuple[str, str, str] | None = None,
        *,
        cmap: str | Sequence[str] | None = None,
        clim: tuple[float, float] | None = None,
        cols: int = 4,
        title: str | None = None,
        xlabel: str | None = None,
    ) -> hv.Element | hv.NdLayout:
        """Draw this raster the way `variable` names it. Needs the `viz` extra.

        Three names give a composite, one gives an Image, and None falls back
        to a sole variable, then to the ones measuring red, green, and blue.
        A `Legend` the variable carries supplies the class and colour maps.

        Args:
            variable: One data variable, three ordered red, green, blue, or
                None to read what this raster carries.
            cmap: Colormap. Refused for a composite, which draws no colormap.
            clim: Bounds mapped onto the full display range: colour limits for
                an Image, the composite's stretch onto `[0, 1]`.
            cols: Columns a `time` axis lays panels into. Ignored otherwise.
            title: Panel title above the axes. None suppresses automatic
                titles.
            xlabel: Location caption below the axes. None uses the raster's
                reverse-geocoded location; an empty string suppresses it.

        Returns:
            Image or RGB element over this raster's grid, or a Layout of one
            panel per `time` value, `cols` wide.

        Raises:
            KeyError: A named variable is absent.
            ValueError: `variable` is None while
                this raster carries more than one variable and measures no
                red, green, and blue among them, two variables measure one
                colour, or the drawing refuses the raster.

        Examples:
            >>> hv.save(ds.gs.plot("ndvi"), "ndvi.png")
            >>> ds.gs.plot("ndvi", cmap="RdYlGn") + ds.gs.plot(clim=(0.0, 0.3))
        """
        # viz/__init__ re-exports a function named plot, shadowing the submodule.
        from geosave_engine.geodata.viz.plot import plot as draw

        if isinstance(variable, str):
            selected: tuple[str, ...] = (variable,)
        elif variable is not None:
            selected = tuple(variable)
        elif len(self.variables) == 1:
            selected = self.variables
        else:
            names = self.variables
            selected = tuple(
                names[band] for band in attrs.GDALVariable.rgb_indices(self._data)
            )

        self._require_variables(selected)
        array = self._data[list(selected)].gs.to_array()

        # A composite carries colour rather than class codes, so it draws no legend.
        legend = None
        if len(selected) == 1:
            legend = attrs.Legend.from_attrs(self._data.variables[selected[0]].attrs)

        place = self.anchor.locate() if xlabel is None else None
        caption = place.to_address() if place is not None else xlabel
        return draw(
            array,
            cmap=cmap,
            clim=clim,
            class_map=legend.class_map if legend else None,
            color_map=legend.color_map if legend else None,
            cols=cols,
            title=title,
            xlabel=caption,
        )

    def to_numpy(self, *, dtype: DTypeLike | None = None) -> np.ndarray:
        """Stack every variable this raster carries into one model-input array.

        Every axis besides the grid leads, then the variables, then the grid
        pair — torchgeo's `[T, C, H, W]`. No batch axis is added, so one raster
        is one sample. Order the variables with xarray before stacking them.

        Args:
            dtype: Cast applied to the stacked array. None keeps the source
                dtype, which every variable must then share.

        Returns:
            Array shaped `(*axes, band, y, x)`.

        Raises:
            ValueError: This raster carries no variables, they carry different
                non-spatial dimensions, or they differ in dtype while `dtype`
                is None.

        Examples:
            >>> ds[["B04", "B08"]].gs.to_numpy().shape
            (2, 4, 256, 256)
        """
        return self._stacked(dtype).values

    def _stacked(self, dtype: DTypeLike | None) -> xr.DataArray:
        """Stack every variable onto the band axis, in the order held.

        Args:
            dtype: Cast applied to the stack. None keeps the source dtype,
                which every variable must then share.

        Returns:
            Array shaped `(*axes, band, y, x)`, carrying no attrs.

        Raises:
            ValueError: This raster carries no variables or already spans the
                band axis, a variable does not span the grid, the variables
                carry different axes, or they differ in dtype while `dtype` is
                None.
        """
        var_names = self.variables
        if not var_names:
            raise ValueError(
                "this raster carries no variables to stack; it holds only coordinates"
            )

        if BAND_DIMENSION in self._data.dims:
            raise ValueError(
                f"this raster already carries a {BAND_DIMENSION!r} dimension, "
                f"which the stacked variables would name; rename it first"
            )

        ungridded = sorted(
            name
            for name in var_names
            if not set(SPATIAL_DIMENSIONS) <= set(self._data.variables[name].dims)
        )
        if ungridded:
            raise ValueError(
                f"{ungridded} do not span the grid {list(SPATIAL_DIMENSIONS)}, so stacking "
                f"them would repeat one value across every pixel; drop them or "
                f"place them on the grid first"
            )

        # Past the grid, the variables must span the same axes to stack.
        axes: dict[str, tuple[str, ...]] = {}
        for name in var_names:
            dims = self._data.variables[name].dims
            axes[name] = tuple(
                str(dim) for dim in dims if dim not in SPATIAL_DIMENSIONS
            )

        drifted = sorted(
            name for name in var_names[1:] if axes[name] != axes[var_names[0]]
        )
        if drifted:
            raise ValueError(
                f"{drifted} carry different axes from {var_names[0]!r}'s "
                f"{axes[var_names[0]]}; stack variables sharing one shape"
            )

        # Stacking promotes silently, so disagreeing dtypes are refused ahead of it.
        dtypes = {str(self._data.variables[name].dtype) for name in var_names}
        if dtype is None and len(dtypes) > 1:
            raise ValueError(
                f"{list(var_names)} carry different dtypes ({sorted(dtypes)}); stacking "
                f"them would promote them, so pass dtype= to choose one"
            )

        # A model reads the grid last, bands right before it: [T, C, H, W].
        stacked = (
            self._data[list(var_names)]
            .to_dataarray(dim=BAND_DIMENSION)
            .transpose(*axes[var_names[0]], BAND_DIMENSION, *SPATIAL_DIMENSIONS)
        )
        return stacked if dtype is None else stacked.astype(dtype)

    def to_cog(
        self,
        path: str | PathLike[str],
        *,
        split_bands: bool = False,
        map_scale: float | None = None,
        overwrite: bool = False,
        storage_options: StorageOptions | None = None,
        **options: Unpack[COGWriteOptions],
    ) -> tuple[Path | str, ...]:
        """Write this raster as Cloud Optimized GeoTIFFs named after `path`.

        Args:
            path: Name of the raster, as a local path or fsspec URL without a
                TIFF suffix.
            split_bands: Write a separate COG for each band.
            map_scale: Map denominator for TIFF resolution tags.
            overwrite: Replace existing files.
            storage_options: Options for the filesystem a URL names.
            **options: COG creation options.

        Returns:
            Exactly the files written, in time then variable order.

        Raises:
            ValueError: `path` ends in a TIFF suffix, or the raster cannot be
                arranged as COGs.
            FileExistsError: A file exists and `overwrite` is false.

        Examples:
            >>> ds.gs.to_cog("samples/forest")[0]
            PosixPath('samples/forest/forest_20250601T103031.tif')
        """
        from geosave_engine.geodata.io import cogs

        # The path is a name, so a TIFF suffix would yield `scene.tif.tif`.
        if PurePosixPath(str(path)).suffix.lower() in (".tif", ".tiff"):
            raise ValueError(
                f"{path} names one file, but to_cog names a raster and arranges "
                f"its files; write one file with io.geotiff.write_cog"
            )
        return cogs.write(
            self._data,
            path,
            split_bands=split_bands,
            map_scale=map_scale,
            overwrite=overwrite,
            storage_options=storage_options,
            **options,
        )

    def to_zarr(
        self,
        destination: str | PathLike[str],
        *,
        compute: bool = True,
        overwrite: bool = False,
        **write_options: Unpack[ZarrWriteOptions],
    ) -> Path | str | Delayed:
        """Write this raster to Zarr.

        Args:
            destination: Output path ending in `.zarr`.
            compute: False defers writing pixels.
            overwrite: Replace an existing destination when true.
            **write_options: Supported xarray Zarr write options.

        Returns:
            Destination path, or a delayed task returning it when `compute=False`.

        Raises:
            FileExistsError: The destination exists and overwrite is false.
            TypeError: An option is unsupported.
            ValueError: The destination is invalid.
        """
        from geosave_engine.geodata.io import zarr

        return zarr.write(
            self._data,
            destination,
            compute=compute,
            overwrite=overwrite,
            **write_options,
        )

    def to_netcdf(
        self,
        destination: str | PathLike[str],
        *,
        compute: bool = True,
        engine: NetCDFEngine = "netcdf4",
        overwrite: bool = False,
        storage_options: StorageOptions | None = None,
        **write_options: Unpack[NetCDFWriteOptions],
    ) -> Path | str | Delayed:
        """Write this raster to netCDF.

        Args:
            destination: Output path ending in `.nc`, `.nc4`, or `.cdf`.
            compute: False returns a delayed task that writes and returns its path.
            engine: Concrete xarray netCDF writing engine.
            overwrite: Replace an existing destination when true.
            storage_options: Options for the filesystem a URL names.
            **write_options: Supported xarray netCDF write options.

        Returns:
            Destination path, or a delayed task returning it when `compute=False`.

        Raises:
            FileExistsError: The destination exists and overwrite is false.
            TypeError: An option is unsupported.
            ValueError: The destination is invalid.
        """
        from geosave_engine.geodata.io import netcdf

        return netcdf.write(
            self._data,
            destination,
            compute=compute,
            overwrite=overwrite,
            engine=engine,
            storage_options=storage_options,
            **write_options,
        )
